
'use strict';
const cvs=document.getElementById('game'),ctx=cvs.getContext('2d'),W=1280,H=720,$=s=>document.querySelector(s);
const keys=new Set();
const stages=[
{name:'ふたりの距離',tag:'発見 / 糸の張力',text:'ほどけた草原で、二匹は初めて一本の糸につながる。三組の縫い目へ同時に立ち、距離と張力を身体で覚える。',steps:['二匹が同じ色の縫い目へ同時に立つ','離れすぎると糸が張り、互いを引き戻す','針や裂け目に触れると倒れる。相手の近くで能力を押して救助'],type:'stitch'},
{name:'一枚の空',tag:'二人持ち / 役割交代',text:'風に裂かれた大布を、二匹で運ぶ。ブルーノは重さを支え、ミミは狭い道から風留めを外す。',steps:['布の両端で二匹が能力を押して持ち上げる','二匹の歩調が合うほど速く運べる','途中の狭い道はミミが先行して風留めを外す'],type:'carry'},
{name:'ほつれから逃げろ',tag:'追跡 / 救助',text:'巨大なほつれが草原を飲み込む。フックを通過しながら走り、倒れた相手を置いていかず出口まで逃げ切る。',steps:['左から迫る黒いほつれより先へ進む','三つのフックを二匹で通過すると安全帯が伸びる','片方が倒れたら、近くで能力を押して即座に救助'],type:'chase'},
{name:'大織機の心臓',tag:'ボス / 集大成',text:'草原をほどき続ける巨大織機。柱へ糸を巻き、弱点を裂き、最後の二つの針を同時に打ち込む。',steps:['第1段階：三本の柱へ糸を触れさせる','第2段階：光る弱点を糸で横切る','最終段階：左右の針台へ二匹が同時に立つ'],type:'boss'}
];
const saveKey='seamThreadMeadowV4';
function loadSave(){try{return JSON.parse(localStorage.getItem(saveKey)||'{\"unlocked\":1,\"best\":{}}')}catch(e){return{unlocked:1,best:{}}}}
function storeSave(){try{localStorage.setItem(saveKey,JSON.stringify(save))}catch(e){}}
let save=loadSave();
let audio=null,master=null,ambient=null;
function ensureAudio(){if(!audio){audio=new (window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=.38;master.connect(audio.destination)}return audio}
function tone(f,d=.1,type='sine',g=.05,delay=0,slide=0){const a=ensureAudio(),o=a.createOscillator(),v=a.createGain();o.type=type;o.frequency.setValueAtTime(f,a.currentTime+delay);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(20,f+slide),a.currentTime+delay+d);v.gain.setValueAtTime(.0001,a.currentTime+delay);v.gain.linearRampToValueAtTime(g,a.currentTime+delay+.012);v.gain.exponentialRampToValueAtTime(.0001,a.currentTime+delay+d);o.connect(v);v.connect(master);o.start(a.currentTime+delay);o.stop(a.currentTime+delay+d+.03)}
function startAmbience(){if(ambient)return;const a=ensureAudio(),g=a.createGain(),o1=a.createOscillator(),o2=a.createOscillator();g.gain.value=.012;o1.type='sine';o2.type='triangle';o1.frequency.value=55;o2.frequency.value=82.4;o1.connect(g);o2.connect(g);g.connect(master);o1.start();o2.start();ambient={g,o1,o2}}
function sfx(n){if(n==='step')tone(105+Math.random()*20,.055,'triangle',.015);if(n==='ability'){tone(430,.09,'sine',.04,0,90);tone(690,.12,'sine',.025,.025,-80)}if(n==='hit'){tone(95,.16,'sawtooth',.075,0,-45);tone(52,.26,'square',.035)}if(n==='rescue'){[330,440,660].forEach((f,i)=>tone(f,.23,'sine',.04,i*.05,50))}if(n==='seal'){tone(510,.14,'triangle',.045);tone(690,.18,'triangle',.035,.04);tone(890,.22,'sine',.03,.08)}if(n==='clear'){[330,440,550,660,880].forEach((f,i)=>tone(f,.38,'sine',.043,i*.075,30))}if(n==='boss'){tone(65,.65,'sawtooth',.06);tone(130,.42,'square',.028,.08,-35)}if(n==='wind'){tone(170,.18,'sine',.018,0,100)}}
const state={mode:'title',stage:0,time:0,rescues:0,progress:0,players:[],objects:{},particles:[],shake:0,flash:0,paused:false,complete:false,intro:0,hitstop:0,lastFoot:[0,0],wind:0};
function player(id,x,y,r){return{id,x,y,vx:0,vy:0,r,speed:id===1?205:252,down:0,revive:0,ability:false,face:1,bob:0,walk:0}}
function show(id){['title','stageSelect','brief','pause','result'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));$('#hud').classList.toggle('hidden',id!=='none')}
function renderStages(){const g=$('#stageGrid');g.innerHTML='';stages.forEach((s,i)=>{const b=document.createElement('button');b.className='stage-card'+(i>=save.unlocked?' locked':'');b.dataset.stage=String(i+1);b.innerHTML=`<div class="num">STAGE ${String(i+1).padStart(2,'0')}</div><h3>${s.name}</h3><div class="mini"></div><p>${s.text}</p><div class="tag">${i>=save.unlocked?'未解放':s.tag}</div>`;b.onclick=()=>{if(i>=save.unlocked)return;state.stage=i;openBrief()};g.appendChild(b)})}
function briefSVG(stage){const tint=['#6fd8c8','#f0b767','#d8e6c4','#b58a55'][stage];return `<svg viewBox="0 0 460 540" role="img" aria-label="${stages[stage].name}の情景"><defs><linearGradient id="bgs" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#5d9b7f"/><stop offset="1" stop-color="#0e2b23"/></linearGradient></defs><rect width="460" height="540" fill="url(#bgs)"/><path d="M0 350 Q120 250 240 350 T500 320 V540 H0Z" fill="#41664c"/><path d="M0 430 Q120 340 250 430 T500 400 V540 H0Z" fill="#213f34"/><circle cx="350" cy="105" r="54" fill="${tint}" opacity=".35"/><g stroke="#eafbf4" stroke-dasharray="5 8" opacity=".25" fill="none"><path d="M-20 180 Q160 100 480 190"/><path d="M-30 270 Q170 330 490 245"/></g><g transform="translate(80 255)"><circle cx="48" cy="30" r="20" fill="#4e704f"/><circle cx="100" cy="30" r="20" fill="#4e704f"/><path d="M40 48 Q75 15 108 50 L118 160 Q75 196 30 158Z" fill="#66875d" stroke="#173429" stroke-width="5"/><ellipse cx="75" cy="72" rx="42" ry="36" fill="#78966e"/><ellipse cx="75" cy="90" rx="28" ry="18" fill="#c4aa7f"/><circle cx="60" cy="69" r="4"/><circle cx="90" cy="69" r="4"/><path d="M43 117 Q75 139 108 115" stroke="#74e1cf" stroke-width="9" fill="none"/></g><g transform="translate(270 300)"><path d="M35 45 Q20 1 39 -9 Q58 20 55 49" fill="#d2b7a5" stroke="#60483d" stroke-width="4"/><path d="M67 48 Q70 3 91 -4 Q99 27 81 59" fill="#d8bdab" stroke="#60483d" stroke-width="4"/><path d="M31 51 Q59 25 88 55 L95 132 Q62 162 25 133Z" fill="#d0b5a3" stroke="#60483d" stroke-width="4"/><ellipse cx="60" cy="71" rx="32" ry="27" fill="#dfc9b6"/><circle cx="49" cy="68" r="3"/><circle cx="72" cy="68" r="3"/><path d="M31 105 Q60 122 90 104" stroke="#f3bd6b" stroke-width="8" fill="none"/></g><path d="M187 365 Q236 330 290 375" stroke="#fff" stroke-width="3" fill="none"/><path d="M187 365 Q236 330 290 375" stroke="${tint}" stroke-width="1.5" fill="none"/></svg>`}
function openBrief(){const s=stages[state.stage];$('#briefNo').textContent=`THREAD MEADOW / STAGE ${String(state.stage+1).padStart(2,'0')}`;$('#briefTitle').textContent=s.name;$('#briefText').textContent=s.text;$('#briefSteps').innerHTML=s.steps.map((x,i)=>`<div class="step"><b>${i+1}</b>${x}</div>`).join('');$('#briefArt').innerHTML=briefSVG(state.stage);show('brief')}
function initStage(){state.mode='play';state.time=0;state.rescues=0;state.progress=0;state.complete=false;state.particles=[];state.shake=0;state.flash=0;state.hitstop=0;state.players=[player(1,150,560,32),player(2,270,560,24)];const t=stages[state.stage].type;state.objects={hazards:[],walls:[],seals:[],hooks:[],cloth:null,windLatch:null,boss:null,exit:{x:1120,y:510,w:105,h:108,open:false}};
if(t==='stitch'){state.objects.seals=[{a:{x:245,y:250},b:{x:410,y:250},done:false},{a:{x:550,y:430},b:{x:720,y:430},done:false},{a:{x:850,y:225},b:{x:1015,y:225},done:false}];state.objects.hazards=[{x:470,y:130,w:30,h:380},{x:770,y:320,w:30,h:290}]}
if(t==='carry'){state.players[0].x=135;state.players[1].x=250;state.objects.cloth={x:350,y:430,w:230,h:90,held:false,delivered:false};state.objects.windLatch={x:720,y:185,r:34,done:false};state.objects.walls=[{x:620,y:110,w:50,h:410,smallPass:true},{x:880,y:330,w:44,h:290}];state.objects.exit={x:1090,y:130,w:110,h:110,open:false}}
if(t==='chase'){state.objects.hooks=[{x:410,y:210,done:false},{x:700,y:500,done:false},{x:980,y:210,done:false}];state.objects.hazards=[{x:560,y:145,w:32,h:300},{x:820,y:320,w:32,h:300}];state.objects.chaseX=-120;state.objects.exit={x:1130,y:510,w:90,h:108,open:true}}
if(t==='boss'){state.players[0].x=160;state.players[1].x=1120;state.objects.boss={phase:1,pylons:[{x:320,y:210,done:false},{x:640,y:510,done:false},{x:960,y:210,done:false}],weak:[{x:430,y:370,done:false},{x:640,y:250,done:false},{x:850,y:370,done:false}],pads:[{x:255,y:520,r:42},{x:1025,y:520,r:42}],pulse:0};state.objects.exit={x:590,y:320,w:100,h:100,open:false}}
$('#stageName').textContent=`WORLD 01 / STAGE ${String(state.stage+1).padStart(2,'0')} — ${stages[state.stage].name}`;show('none');stageIntro();ensureAudio().resume();startAmbience()}
function stageIntro(){state.intro=2.3;$('#stageTitle').querySelector('h2').textContent=stages[state.stage].name;$('#stageTitle').querySelector('p').textContent=stages[state.stage].tag;$('#cinema').classList.add('on');$('#stageTitle').classList.add('show');setTimeout(()=>{$('#cinema').classList.remove('on');$('#stageTitle').classList.remove('show')},1850)}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),1750)}
function burst(x,y,color,n=16,speed=170){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=40+Math.random()*speed;state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.45+Math.random()*.7,size:2+Math.random()*5,color,shape:Math.random()>.55?'thread':'dot'})}}
function circleRect(p,r){const nx=Math.max(r.x,Math.min(p.x,r.x+r.w)),ny=Math.max(r.y,Math.min(p.y,r.y+r.h));return Math.hypot(p.x-nx,p.y-ny)<p.r}
function movePlayer(p,dx,dy,dt){if(p.down>0)return;let m=Math.hypot(dx,dy);if(m){dx/=m;dy/=m;p.vx=dx*p.speed;p.vy=dy*p.speed;p.face=dx?Math.sign(dx):p.face;p.bob+=dt*9;p.walk=Math.min(1,p.walk+dt*6);const now=performance.now();if(now-state.lastFoot[p.id-1]>230){state.lastFoot[p.id-1]=now;sfx('step');burst(p.x,p.y+p.r*.65,p.id===1?'#7ba668':'#d9c0a6',3,45)}}else{p.vx*=.76;p.vy*=.76;p.walk=Math.max(0,p.walk-dt*5)}p.x+=p.vx*dt;p.y+=p.vy*dt;p.x=Math.max(55,Math.min(W-55,p.x));p.y=Math.max(95,Math.min(H-56,p.y));for(const w of state.objects.walls||[]){if(w.smallPass&&p.id===2)continue;if(circleRect(p,w)){p.x-=p.vx*dt;p.y-=p.vy*dt;p.vx=p.vy=0}}}
function downPlayer(p){if(p.down>0)return;p.down=5;p.vx=p.vy=0;state.shake=11;state.flash=.34;state.hitstop=.08;sfx('hit');burst(p.x,p.y,'#ef746f',30,220);toast(`${p.id===1?'ブルーノ':'ミミ'}が倒れた。近くで能力を長押し！`)}
function updateRevive(dt){const [a,b]=state.players;for(const [down,helper] of [[a,b],[b,a]]){if(down.down<=0)continue;down.down-=dt;const d=Math.hypot(down.x-helper.x,down.y-helper.y);if(d<105&&helper.ability){down.revive+=dt;if(down.revive>=.85){down.down=0;down.revive=0;down.x=helper.x+(down.id===1?-58:58);down.y=helper.y;state.rescues++;state.hitstop=.12;sfx('rescue');burst(down.x,down.y,'#d9f7d0',40,230);toast('救助成功！')}}else down.revive=Math.max(0,down.revive-dt*.5);if(down.down<=.01)resetStage()}}
function tether(dt){const [a,b]=state.players,dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,max=330;if(d>max){const pull=(d-max)*4.3,nx=dx/d,ny=dy/d;if(a.down<=0){a.x+=nx*pull*dt;a.y+=ny*pull*dt}if(b.down<=0){b.x-=nx*pull*dt;b.y-=ny*pull*dt}}}
function segPoint(a,b,p){const vx=b.x-a.x,vy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*vx+(p.y-a.y)*vy)/(vx*vx+vy*vy||1)));return Math.hypot(p.x-(a.x+vx*t),p.y-(a.y+vy*t))}
function updateStage(dt){const [a,b]=state.players,t=stages[state.stage].type;a.ability=keys.has('KeyQ');b.ability=keys.has('Enter');
if(t==='stitch'){let done=0;state.objects.seals.forEach(s=>{if(s.done){done++;return}const ok=(Math.hypot(a.x-s.a.x,a.y-s.a.y)<42&&Math.hypot(b.x-s.b.x,b.y-s.b.y)<42)||(Math.hypot(b.x-s.a.x,b.y-s.a.y)<42&&Math.hypot(a.x-s.b.x,a.y-s.b.y)<42);if(ok){s.done=true;sfx('seal');state.hitstop=.1;burst((s.a.x+s.b.x)/2,(s.a.y+s.b.y)/2,'#87e8d9',38,210);state.shake=6;done++;toast('縫い目がつながった')}});state.progress=done/3;state.objects.exit.open=done===3;$('#objective').textContent=done===3?'出口へ二匹で入る':`縫い目を結ぶ ${done}/3`}
if(t==='carry'){const c=state.objects.cloth,l=state.objects.windLatch;const da=Math.hypot(a.x-(c.x-55),a.y-c.y),db=Math.hypot(b.x-(c.x+55),b.y-c.y);if(!c.delivered&&a.ability&&b.ability&&da<90&&db<90){if(!c.held)sfx('ability');c.held=true}if(c.held){const mx=(a.x+b.x)/2,my=(a.y+b.y)/2;c.x+=(mx-c.x)*dt*4;c.y+=(my-c.y)*dt*4;if(!(a.ability&&b.ability)||Math.hypot(a.x-b.x,a.y-b.y)>300)c.held=false}if(!l.done&&Math.hypot(b.x-l.x,b.y-l.y)<55&&b.ability){l.done=true;state.hitstop=.08;sfx('seal');burst(l.x,l.y,'#f0b767',32,190);toast('風留めを外した')}if(l.done&&c.x>950&&c.y<300){c.delivered=true;c.held=false;state.objects.exit.open=true;sfx('seal');burst(c.x,c.y,'#fff0bd',48,240)}state.progress=(l.done?.45:0)+(c.delivered?.55:0);$('#objective').textContent=!l.done?'ミミが風留めを外す':!c.delivered?'二匹で大布を高台へ運ぶ':'出口へ二匹で入る'}
if(t==='chase'){state.objects.chaseX+=dt*(75+state.time*.8);for(const p of state.players)if(p.x<state.objects.chaseX+70)downPlayer(p);let n=0;state.objects.hooks.forEach(h=>{if(h.done){n++;return}if(Math.hypot(a.x-h.x,a.y-h.y)<55&&Math.hypot(b.x-h.x,b.y-h.y)<80){h.done=true;n++;state.hitstop=.06;sfx('seal');burst(h.x,h.y,'#f0b767',34,210);toast('安全帯を延長')}});state.progress=n/3;$('#objective').textContent=`ほつれから逃げる / フック ${n}/3`}
if(t==='boss'){const o=state.objects.boss;o.pulse+=dt;if(o.phase===1){let n=0;o.pylons.forEach(p=>{if(!p.done&&segPoint(a,b,p)<26){p.done=true;sfx('seal');state.hitstop=.09;burst(p.x,p.y,'#6fd8c8',38,220);state.shake=7}if(p.done)n++});state.progress=n/3;$('#objective').textContent=`糸を柱へ巻く ${n}/3`;if(n===3){o.phase=2;sfx('boss');toast('織機の弱点が露出した')}}else if(o.phase===2){let n=0;o.weak.forEach(p=>{if(!p.done&&segPoint(a,b,p)<20&&Math.hypot(a.x-b.x,a.y-b.y)>230){p.done=true;sfx('hit');state.hitstop=.14;burst(p.x,p.y,'#ffcf82',50,260);state.shake=15;state.flash=.48}if(p.done)n++});state.progress=n/3;$('#objective').textContent=`張った糸で弱点を裂く ${n}/3`;if(n===3){o.phase=3;sfx('boss');toast('最後の二本の針を同時に打ち込め')}}else{const pa=Math.hypot(a.x-o.pads[0].x,a.y-o.pads[0].y)<50,pb=Math.hypot(b.x-o.pads[1].x,b.y-o.pads[1].y)<50,swap=Math.hypot(b.x-o.pads[0].x,b.y-o.pads[0].y)<50&&Math.hypot(a.x-o.pads[1].x,a.y-o.pads[1].y)<50;state.progress=(pa&&pb)||swap?1:0;$('#objective').textContent='左右の針台へ同時に立つ';if((pa&&pb)||swap){state.objects.exit.open=true;setTimeout(()=>completeStage(),420)}}}
for(const h of state.objects.hazards||[])for(const p of state.players)if(circleRect(p,h))downPlayer(p);if(state.objects.exit.open){const e=state.objects.exit,inside=state.players.every(p=>p.x>e.x&&p.x<e.x+e.w&&p.y>e.y&&p.y<e.y+e.h);if(inside&&t!=='boss')completeStage()}}
function update(dt){if(state.mode!=='play'||state.paused||state.complete)return;if(state.hitstop>0){state.hitstop-=dt;return}state.time+=dt;state.intro=Math.max(0,state.intro-dt);state.wind+=dt;const a=state.players[0],b=state.players[1];movePlayer(a,(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0),dt);movePlayer(b,(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0),(keys.has('ArrowDown')?1:0)-(keys.has('ArrowUp')?1:0),dt);tether(dt);updateRevive(dt);updateStage(dt);state.particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;p.life-=dt});state.particles=state.particles.filter(p=>p.life>0);state.shake=Math.max(0,state.shake-dt*30);state.flash=Math.max(0,state.flash-dt*2);$('#time').textContent=fmt(state.time);$('#rescues').textContent=state.rescues;$('#progress').style.width=(state.progress*100)+'%'}
function fmt(t){const m=Math.floor(t/60),s=Math.floor(t%60);return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function roundRectPath(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function draw(){ctx.save();ctx.clearRect(0,0,W,H);const sx=(Math.random()-.5)*state.shake,sy=(Math.random()-.5)*state.shake;ctx.translate(sx,sy);drawBackdrop();if(state.mode==='play'){drawWorld();drawTether();drawPlayers();drawParticles();if(state.flash){ctx.fillStyle=`rgba(255,255,255,${state.flash})`;ctx.fillRect(0,0,W,H)}}ctx.restore()}
function fabricPattern(alpha=.09){ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle='#fff';ctx.lineWidth=1;for(let y=0;y<H;y+=18){ctx.beginPath();ctx.moveTo(0,y);for(let x=0;x<=W;x+=26)ctx.lineTo(x,y+Math.sin(x*.035+y*.02)*2);ctx.stroke()}ctx.strokeStyle='#000';for(let x=0;x<W;x+=23){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+Math.sin(x)*3,H);ctx.stroke()}ctx.restore()}
function drawBackdrop(){const st=state.mode==='play'?state.stage:0;const top=['#4f9276','#688c77','#456c61','#202f2c'][st],mid=['#2e624f','#496b58','#294c43','#1a2927'][st],bot=['#142f27','#203e34','#132824','#0a1514'][st];const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,top);g.addColorStop(.55,mid);g.addColorStop(1,bot);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);fabricPattern(.055);
// stitched clouds
for(let i=0;i<5;i++){const x=120+i*270+Math.sin(state.wind*.12+i)*18,y=105+(i%2)*55;ctx.save();ctx.globalAlpha=.18;ctx.fillStyle='#e8f4dc';ctx.beginPath();ctx.ellipse(x,y,70,25,0,0,Math.PI*2);ctx.ellipse(x+55,y+7,48,20,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffffff88';ctx.setLineDash([5,8]);ctx.stroke();ctx.restore()}
// distant stitched hills
ctx.fillStyle=st===3?'#26332e':'#496f50';ctx.beginPath();ctx.moveTo(0,470);for(let x=0;x<=W;x+=80)ctx.lineTo(x,390+Math.sin(x*.009+st)*55);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();ctx.strokeStyle='#d9efcf3c';ctx.lineWidth=2;ctx.setLineDash([7,10]);ctx.stroke();ctx.setLineDash([]);
ctx.fillStyle=st===2?'#1f332d':'#2d5845';ctx.beginPath();ctx.moveTo(0,555);for(let x=0;x<=W;x+=60)ctx.lineTo(x,500+Math.sin(x*.012+1.2)*40);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();
// world landmarks
if(st===0){for(let i=0;i<4;i++)drawSpool(80+i*360,420+(i%2)*35,.55)}
if(st===1){for(let i=0;i<5;i++)drawRibbon(140+i*240,130+(i%2)*80,40+i*7)}
if(st===2){ctx.fillStyle='#050a09aa';ctx.beginPath();ctx.moveTo(0,150);for(let x=0;x<420;x+=22)ctx.lineTo(x,150+Math.sin(x*.07+state.time*4)*25);ctx.lineTo(0,H);ctx.fill()}
if(st===3){drawLoomBackdrop()}
ctx.fillStyle='#183b2e';ctx.fillRect(0,612,W,108);ctx.strokeStyle='#8dbb7f38';ctx.lineWidth=2;for(let y=625;y<720;y+=17){ctx.beginPath();ctx.moveTo(0,y);for(let x=0;x<=W;x+=38)ctx.lineTo(x,y+Math.sin(x*.022+y)*4);ctx.stroke()}
for(let i=0;i<70;i++){const x=(i*97)%W,y=600+((i*43)%100),h=8+(i%6)*4;ctx.strokeStyle=i%4?'#6e9658':'#e0be66';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+Math.sin(state.wind*2+i)*5,y-h/2,x+Math.sin(state.wind*2+i)*8,y-h);ctx.stroke()}}
function drawSpool(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='#6d4d33';ctx.beginPath();ctx.ellipse(0,-34,48,15,0,0,Math.PI*2);ctx.fill();ctx.fillRect(-35,-34,70,68);ctx.beginPath();ctx.ellipse(0,34,48,15,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f0b767';ctx.lineWidth=5;for(let yy=-22;yy<27;yy+=8){ctx.beginPath();ctx.moveTo(-32,yy);ctx.lineTo(32,yy+4);ctx.stroke()}ctx.restore()}
function drawRibbon(x,y,l){ctx.save();ctx.translate(x,y);ctx.strokeStyle='#f5d38b77';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,0);for(let i=0;i<=l;i+=5)ctx.lineTo(i*2,Math.sin(i*.22+state.wind*2)*10);ctx.stroke();ctx.restore()}
function drawLoomBackdrop(){ctx.save();ctx.globalAlpha=.32;ctx.fillStyle='#0b1412';ctx.fillRect(330,105,620,420);ctx.strokeStyle='#aa7a47';ctx.lineWidth=14;ctx.strokeRect(360,120,560,390);for(let x=405;x<900;x+=45){ctx.strokeStyle='#d2b17c55';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,130);ctx.lineTo(x,500);ctx.stroke()}ctx.restore()}
function drawWorld(){const o=state.objects,t=stages[state.stage].type;for(const w of o.walls||[])drawWall(w);for(const h of o.hazards||[])drawHazard(h);if(t==='stitch')o.seals.forEach(drawSeal);if(t==='carry'){drawCloth(o.cloth);drawLatch(o.windLatch)}if(t==='chase'){ctx.fillStyle='#050808';ctx.fillRect(0,90,o.chaseX+60,H-90);ctx.strokeStyle='#ee746f';ctx.lineWidth=7;ctx.shadowBlur=16;ctx.shadowColor='#ee746f';ctx.beginPath();ctx.moveTo(o.chaseX+60,90);for(let y=90;y<H;y+=20)ctx.lineTo(o.chaseX+60+Math.sin(y*.09+state.time*5)*15,y);ctx.stroke();ctx.shadowBlur=0;o.hooks.forEach(drawHook)}if(t==='boss')drawBoss(o.boss);drawExit(o.exit)}
function drawWall(w){ctx.save();ctx.fillStyle='#315346';ctx.strokeStyle='#b6dfce66';ctx.lineWidth=4;roundRectPath(w.x,w.y,w.w,w.h,15);ctx.fill();ctx.stroke();ctx.strokeStyle='#ffffff13';for(let y=w.y+17;y<w.y+w.h;y+=24){ctx.beginPath();ctx.moveTo(w.x+7,y);ctx.lineTo(w.x+w.w-7,y+8);ctx.stroke()}ctx.fillStyle='#9fc48a33';for(let y=w.y+12;y<w.y+w.h;y+=46){ctx.beginPath();ctx.arc(w.x+w.w/2,y,4,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawHazard(h){ctx.save();ctx.translate(h.x+h.w/2,h.y+h.h/2);ctx.fillStyle='#130f13';ctx.strokeStyle='#ef746fcc';ctx.lineWidth=3;roundRectPath(-h.w/2,-h.h/2,h.w,h.h,8);ctx.fill();ctx.stroke();for(let y=-h.h/2+18;y<h.h/2;y+=35){ctx.fillStyle='#c9d3ce';ctx.beginPath();ctx.moveTo(-h.w/2-10,y+12);ctx.lineTo(h.w/2+12,y-12);ctx.lineTo(h.w/2+7,y+5);ctx.closePath();ctx.fill();ctx.fillStyle='#ef746f';ctx.beginPath();ctx.arc(-h.w/2-8,y+14,5,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawSeal(s){for(const [p,col] of [[s.a,'#6fd8c8'],[s.b,'#f0b767']]){ctx.save();ctx.translate(p.x,p.y);ctx.strokeStyle=s.done?'#e2fff1':col;ctx.lineWidth=6;ctx.shadowBlur=s.done?25:14;ctx.shadowColor=col;ctx.beginPath();ctx.arc(0,0,30,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#7a5237';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,36,0,Math.PI*2);ctx.stroke();ctx.strokeStyle=col;ctx.lineWidth=2;for(let i=0;i<10;i++){const a=i*Math.PI/5;ctx.beginPath();ctx.moveTo(Math.cos(a)*18,Math.sin(a)*18);ctx.lineTo(Math.cos(a)*32,Math.sin(a)*32);ctx.stroke()}ctx.restore()}if(s.done){ctx.strokeStyle='#e9fff1';ctx.lineWidth=5;ctx.shadowBlur=14;ctx.shadowColor='#a8f5e2';ctx.beginPath();ctx.moveTo(s.a.x,s.a.y);ctx.quadraticCurveTo((s.a.x+s.b.x)/2,(s.a.y+s.b.y)/2-30,s.b.x,s.b.y);ctx.stroke();ctx.shadowBlur=0}}
function drawCloth(c){ctx.save();ctx.translate(c.x,c.y);ctx.fillStyle=c.delivered?'#f6e4b0':'#d9bf83';ctx.strokeStyle='#fff1be';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-c.w/2,-c.h/2);ctx.quadraticCurveTo(0,-c.h/2-20,c.w/2,-c.h/2);ctx.lineTo(c.w/2,c.h/2);ctx.quadraticCurveTo(0,c.h/2+20,-c.w/2,c.h/2);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle='#795d37';ctx.lineWidth=3;for(let x=-95;x<105;x+=30){ctx.beginPath();ctx.moveTo(x,-34);ctx.lineTo(x+20,34);ctx.stroke()}for(let x=-100;x<=100;x+=25){ctx.strokeStyle='#fff3c4';ctx.beginPath();ctx.moveTo(x,45);ctx.lineTo(x+Math.sin(state.time*3+x)*4,58);ctx.stroke()}ctx.restore()}
function drawLatch(l){ctx.save();ctx.translate(l.x,l.y);ctx.rotate(state.time*(l.done?.3:1.2));for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.fillStyle=l.done?'#8ce3d2':'#f3bd6b';ctx.beginPath();ctx.ellipse(20,0,18,7,0,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#17332d';ctx.beginPath();ctx.arc(0,0,12,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawHook(h){ctx.save();ctx.translate(h.x,h.y);ctx.strokeStyle=h.done?'#e3fff0':'#f3bd6b';ctx.lineWidth=8;ctx.shadowBlur=18;ctx.shadowColor=ctx.strokeStyle;ctx.beginPath();ctx.arc(0,0,30,.25,Math.PI*1.83);ctx.stroke();ctx.beginPath();ctx.moveTo(21,-21);ctx.lineTo(33,-36);ctx.stroke();ctx.fillStyle='#7a5338';ctx.beginPath();ctx.arc(0,0,7,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawBoss(o){ctx.save();ctx.translate(640,310);ctx.fillStyle='#111916';ctx.strokeStyle='#b77d43';ctx.lineWidth=11;ctx.beginPath();ctx.arc(0,0,142,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle='#e2bd7b66';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,104,0,Math.PI*2);ctx.stroke();ctx.rotate(state.time*.22);for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.fillStyle=i%2?'#40564d':'#2b3d37';roundRectPath(100,-17,102,34,8);ctx.fill();ctx.strokeStyle='#91704d';ctx.stroke()}ctx.fillStyle='#c39a62';ctx.beginPath();ctx.arc(0,0,42,0,Math.PI*2);ctx.fill();ctx.fillStyle='#19211e';ctx.beginPath();ctx.arc(0,0,19,0,Math.PI*2);ctx.fill();ctx.restore();o.pylons.forEach(p=>{ctx.fillStyle=p.done?'#6fd8c8':'#36564e';ctx.strokeStyle='#c6f5e9';ctx.lineWidth=4;ctx.beginPath();ctx.arc(p.x,p.y,26,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle='#79583a';ctx.lineWidth=5;ctx.beginPath();ctx.arc(p.x,p.y,34,0,Math.PI*2);ctx.stroke()});o.weak.forEach(p=>{if(p.done)return;ctx.fillStyle='#f3bd6b';ctx.shadowBlur=28;ctx.shadowColor='#f3bd6b';ctx.beginPath();ctx.arc(p.x,p.y,18+Math.sin(state.time*5)*3,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0});if(o.phase===3)o.pads.forEach((p,i)=>{ctx.strokeStyle=i?'#f3bd6b':'#6fd8c8';ctx.lineWidth=7;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.stroke();for(let k=0;k<6;k++){const a=k*Math.PI/3;ctx.beginPath();ctx.moveTo(p.x+Math.cos(a)*24,p.y+Math.sin(a)*24);ctx.lineTo(p.x+Math.cos(a)*39,p.y+Math.sin(a)*39);ctx.stroke()}})}
function drawExit(e){ctx.save();ctx.translate(e.x+e.w/2,e.y+e.h/2);ctx.globalAlpha=e.open?1:.32;ctx.strokeStyle=e.open?'#e2fff1':'#75847f';ctx.lineWidth=7;ctx.shadowBlur=e.open?28:0;ctx.shadowColor='#6fd8c8';roundRectPath(-e.w/2,-e.h/2,e.w,e.h,27);ctx.stroke();ctx.fillStyle=e.open?'#6fd8c82b':'#0002';ctx.fill();ctx.strokeStyle=e.open?'#f3bd6b':'#79867f';ctx.lineWidth=2;ctx.setLineDash([5,7]);roundRectPath(-e.w/2+10,-e.h/2+10,e.w-20,e.h-20,20);ctx.stroke();ctx.setLineDash([]);ctx.restore()}
function drawTether(){const [a,b]=state.players,d=Math.hypot(a.x-b.x,a.y-b.y),ten=Math.max(0,(d-210)/120);ctx.save();ctx.strokeStyle=`rgba(230,255,245,${.65+ten*.3})`;ctx.lineWidth=4+ten*4;ctx.shadowBlur=17+ten*19;ctx.shadowColor='#c8fff1';ctx.beginPath();ctx.moveTo(a.x,a.y);const mx=(a.x+b.x)/2,my=(a.y+b.y)/2+Math.sin(state.time*5)*Math.max(4,23-ten*18);ctx.quadraticCurveTo(mx,my,b.x,b.y);ctx.stroke();ctx.strokeStyle=a.id===1?'#6fd8c8':'#f3bd6b';ctx.globalAlpha=.45;ctx.lineWidth=1.4;ctx.setLineDash([5,8]);ctx.stroke();ctx.restore()}
function drawBear(p){const bob=Math.sin(p.bob)*3*p.walk,lean=Math.max(-.16,Math.min(.16,p.vx/700));ctx.save();ctx.translate(p.x,p.y+bob);ctx.scale(p.face,1);ctx.rotate(lean);if(p.down>0){ctx.rotate(.72);ctx.globalAlpha=.58}ctx.fillStyle='#06100c66';ctx.beginPath();ctx.ellipse(0,35,42,14,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#4d6f50';ctx.beginPath();ctx.arc(-28,-37,18,0,Math.PI*2);ctx.arc(28,-37,18,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#183529';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-34,-25);ctx.quadraticCurveTo(0,-62,35,-24);ctx.lineTo(40,25);ctx.quadraticCurveTo(0,55,-42,24);ctx.closePath();ctx.fillStyle='#62805b';ctx.fill();ctx.stroke();ctx.fillStyle='#78946b';ctx.beginPath();ctx.ellipse(0,-16,35,31,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#c3a87f';ctx.beginPath();ctx.ellipse(0,1,24,16,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#101a16';ctx.beginPath();ctx.arc(-13,-19,4.5,0,Math.PI*2);ctx.arc(13,-19,4.5,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-5,-1);ctx.quadraticCurveTo(0,-6,6,-1);ctx.quadraticCurveTo(1,7,-5,-1);ctx.fill();ctx.strokeStyle='#74e1cf';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(-28,13);ctx.quadraticCurveTo(0,27,31,12);ctx.stroke();ctx.beginPath();ctx.moveTo(3,22);ctx.lineTo(15,51);ctx.stroke();ctx.strokeStyle='#4d6f50';ctx.lineWidth=17;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-20,23);ctx.lineTo(-29,44+Math.sin(p.bob)*3*p.walk);ctx.moveTo(20,23);ctx.lineTo(29,44-Math.sin(p.bob)*3*p.walk);ctx.stroke();ctx.strokeStyle='#d8edbd';ctx.lineWidth=3;ctx.setLineDash([4,6]);ctx.beginPath();ctx.moveTo(-22,-43);ctx.quadraticCurveTo(0,-52,22,-42);ctx.stroke();ctx.setLineDash([]);ctx.restore()}
function drawRabbit(p){const bob=Math.sin(p.bob)*4*p.walk,lean=Math.max(-.2,Math.min(.2,p.vx/620));ctx.save();ctx.translate(p.x,p.y+bob);ctx.scale(p.face,1);ctx.rotate(lean);if(p.down>0){ctx.rotate(.82);ctx.globalAlpha=.58}ctx.fillStyle='#06100c66';ctx.beginPath();ctx.ellipse(0,29,31,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d2b7a4';ctx.strokeStyle='#624a3f';ctx.lineWidth=3.5;ctx.beginPath();ctx.moveTo(-18,-39);ctx.quadraticCurveTo(-30,-98,-8,-106);ctx.quadraticCurveTo(9,-70,-3,-33);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(8,-37);ctx.quadraticCurveTo(14,-95,34,-101);ctx.quadraticCurveTo(44,-56,24,-26);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(-28,-25);ctx.quadraticCurveTo(0,-54,30,-24);ctx.lineTo(34,25);ctx.quadraticCurveTo(0,49,-34,24);ctx.closePath();ctx.fillStyle='#cfb39f';ctx.fill();ctx.stroke();ctx.fillStyle='#dec8b6';ctx.beginPath();ctx.ellipse(0,-13,28,24,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f0decb';ctx.beginPath();ctx.ellipse(0,1,18,11,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#281f1c';ctx.beginPath();ctx.arc(-10,-16,3.7,0,Math.PI*2);ctx.arc(10,-16,3.7,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-4,0);ctx.quadraticCurveTo(0,-4,5,0);ctx.quadraticCurveTo(1,5,-4,0);ctx.fill();ctx.strokeStyle='#f3bd6b';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(-24,11);ctx.quadraticCurveTo(0,23,25,10);ctx.stroke();ctx.beginPath();ctx.moveTo(4,18);ctx.lineTo(14,43);ctx.stroke();ctx.strokeStyle='#bea08f';ctx.lineWidth=13;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-14,21);ctx.lineTo(-19,39+Math.sin(p.bob)*4*p.walk);ctx.moveTo(14,21);ctx.lineTo(20,39-Math.sin(p.bob)*4*p.walk);ctx.stroke();ctx.fillStyle='#f2e0d0';ctx.beginPath();ctx.arc(31,18,12,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff0df';ctx.lineWidth=2.5;ctx.setLineDash([4,5]);ctx.beginPath();ctx.moveTo(-19,-31);ctx.quadraticCurveTo(0,-42,20,-30);ctx.stroke();ctx.setLineDash([]);ctx.restore()}
function drawPlayers(){for(const p of state.players){if(p.id===1)drawBear(p);else drawRabbit(p);if(p.down>0){ctx.strokeStyle='#e4fff2';ctx.lineWidth=5;ctx.beginPath();ctx.arc(p.x,p.y,46,-Math.PI/2,-Math.PI/2+Math.PI*2*(p.revive/.85));ctx.stroke()}if(p.ability&&p.down<=0){ctx.strokeStyle=p.id===1?'#6fd8c8':'#f3bd6b';ctx.lineWidth=3;ctx.shadowBlur=14;ctx.shadowColor=ctx.strokeStyle;ctx.beginPath();ctx.arc(p.x,p.y,p.r+17+Math.sin(state.time*8)*3,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0}ctx.fillStyle='#07130fbb';roundRectPath(p.x-37,p.y-73,74,20,10);ctx.fill();ctx.fillStyle=p.id===1?'#9af1e1':'#ffd793';ctx.font='700 10px system-ui';ctx.textAlign='center';ctx.fillText(p.id===1?'BRUNO':'MIMI',p.x,p.y-59)}}
function drawParticles(){state.particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life);ctx.strokeStyle=p.color;ctx.fillStyle=p.color;if(p.shape==='thread'){ctx.lineWidth=Math.max(1,p.size*.45);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-p.vx*.035,p.y-p.vy*.035);ctx.stroke()}else{ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}});ctx.globalAlpha=1}
function completeStage(){if(state.complete)return;state.complete=true;sfx('clear');state.shake=18;state.hitstop=.16;burst(640,340,'#eaffef',130,320);const time=state.time,rank=time<75?'S':time<115?'A':'B';save.best[state.stage]={time,rescues:state.rescues,rank};save.unlocked=Math.max(save.unlocked,Math.min(4,state.stage+2));storeSave();setTimeout(()=>{$('#resultTitle').textContent=stages[state.stage].name+' 修復完了';$('#resultText').textContent=['二匹の距離が、草原の最初の縫い目になった。','一枚の空が、二匹の歩調で元の場所へ戻った。','誰も置いていかず、ほつれの波を越えた。','大織機は止まり、草原は二匹の足音を覚えた。'][state.stage];$('#resultTime').textContent=fmt(time);$('#resultRescues').textContent=state.rescues;$('#resultRank').textContent=rank;$('#next').textContent=state.stage<3?'次のステージ':'ステージ選択';show('result');state.mode='result'},900)}
function resetStage(){initStage()}
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(!e.repeat){if(e.code==='Escape'&&state.mode==='play'){state.paused=true;show('pause')}if(e.code==='KeyR'&&state.mode==='play')resetStage()}},{passive:false});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>keys.clear());
$('#start').onclick=()=>{renderStages();show('stageSelect')};$('#backTitle').onclick=()=>show('title');$('#backStages').onclick=()=>{renderStages();show('stageSelect')};$('#enter').onclick=initStage;$('#resume').onclick=()=>{state.paused=false;show('none')};$('#retry').onclick=resetStage;$('#quit').onclick=()=>{state.mode='menu';renderStages();show('stageSelect')};$('#resultMenu').onclick=()=>{renderStages();show('stageSelect')};$('#next').onclick=()=>{if(state.stage<3){state.stage++;openBrief()}else{renderStages();show('stageSelect')}};$('#resetSave').onclick=()=>{save={unlocked:1,best:{}};storeSave();toast('進行をリセットしました')};
let last=performance.now();function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);renderStages();show('title');
